name: solved-ac_solution
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^2.0.0
